<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="1" failed="1" skipped="1">
  <reporter-output>
    <line>
      <![CDATA[Testng_ReportsAndLogs -> This runs once before class]]>
    </line>
    <line>
      <![CDATA[Testng_ReportsAndLogs -> This runs before every method]]>
    </line>
    <line>
      <![CDATA[Testng_ReportsAndLogs -> testMethod2]]>
    </line>
    <line>
      <![CDATA[Testng_ReportsAndLogs -> This runs after every method]]>
    </line>
    <line>
      <![CDATA[Testng_ReportsAndLogs -> This runs before every method]]>
    </line>
    <line>
      <![CDATA[Testng_ReportsAndLogs -> testMethod1]]>
    </line>
    <line>
      <![CDATA[Testng_ReportsAndLogs -> This runs after every method]]>
    </line>
    <line>
      <![CDATA[Testng_ReportsAndLogs -> This runs once after class]]>
    </line>
  </reporter-output>
  <suite started-at="2024-10-24T12:50:27Z" name="ReportAndLog TestSuite" finished-at="2024-10-24T12:50:27Z" duration-ms="48">
    <groups>
    </groups>
    <test started-at="2024-10-24T12:50:27Z" name="Application test" finished-at="2024-10-24T12:50:27Z" duration-ms="48">
      <class name="Testng_testclasses.Testng_ReportsAndLogs">
        <test-method is-config="true" signature="beforeClass()[pri:0, instance:Testng_testclasses.Testng_ReportsAndLogs@21e360a]" started-at="2024-10-24T18:20:27Z" name="beforeClass" finished-at="2024-10-24T18:20:27Z" duration-ms="5" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Testng_ReportsAndLogs -> This runs once before class]]>
            </line>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:Testng_testclasses.Testng_ReportsAndLogs@21e360a]" started-at="2024-10-24T18:20:27Z" name="beforeMethod" finished-at="2024-10-24T18:20:27Z" duration-ms="1" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Testng_ReportsAndLogs -> This runs before every method]]>
            </line>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="testMethod2()[pri:0, instance:Testng_testclasses.Testng_ReportsAndLogs@21e360a]" started-at="2024-10-24T18:20:27Z" name="testMethod2" finished-at="2024-10-24T18:20:27Z" duration-ms="11" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at org.testng.Assert.assertTrue(Assert.java:51)
	at Testng_testclasses.Testng_ReportsAndLogs.testMethod2(Testng_ReportsAndLogs.java:47)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Testng_ReportsAndLogs -> testMethod2]]>
            </line>
          </reporter-output>
        </test-method> <!-- testMethod2 -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:Testng_testclasses.Testng_ReportsAndLogs@21e360a]" started-at="2024-10-24T18:20:27Z" name="afterMethod" finished-at="2024-10-24T18:20:27Z" duration-ms="2" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Testng_ReportsAndLogs -> This runs after every method]]>
            </line>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:Testng_testclasses.Testng_ReportsAndLogs@21e360a]" started-at="2024-10-24T18:20:27Z" name="beforeMethod" finished-at="2024-10-24T18:20:27Z" duration-ms="1" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Testng_ReportsAndLogs -> This runs before every method]]>
            </line>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="testMethod1()[pri:0, instance:Testng_testclasses.Testng_ReportsAndLogs@21e360a]" started-at="2024-10-24T18:20:27Z" name="testMethod1" finished-at="2024-10-24T18:20:27Z" duration-ms="5" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Testng_ReportsAndLogs -> testMethod1]]>
            </line>
          </reporter-output>
        </test-method> <!-- testMethod1 -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:Testng_testclasses.Testng_ReportsAndLogs@21e360a]" started-at="2024-10-24T18:20:27Z" name="afterMethod" finished-at="2024-10-24T18:20:27Z" duration-ms="1" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Testng_ReportsAndLogs -> This runs after every method]]>
            </line>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method signature="testMethod3()[pri:0, instance:Testng_testclasses.Testng_ReportsAndLogs@21e360a]" started-at="2024-10-24T18:20:27Z" name="testMethod3" finished-at="2024-10-24T18:20:27Z" depends-on-methods="Testng_testclasses.Testng_ReportsAndLogs.testMethod2" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Testng_ReportsAndLogs.testMethod3()[pri:0, instance:Testng_testclasses.Testng_ReportsAndLogs@21e360a] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Testng_ReportsAndLogs.testMethod3()[pri:0, instance:Testng_testclasses.Testng_ReportsAndLogs@21e360a] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1084)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMethod3 -->
        <test-method is-config="true" signature="afterClass()[pri:0, instance:Testng_testclasses.Testng_ReportsAndLogs@21e360a]" started-at="2024-10-24T18:20:27Z" name="afterClass" finished-at="2024-10-24T18:20:27Z" duration-ms="0" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Testng_ReportsAndLogs -> This runs once after class]]>
            </line>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- Testng_testclasses.Testng_ReportsAndLogs -->
    </test> <!-- Application test -->
  </suite> <!-- ReportAndLog TestSuite -->
</testng-results>
